profile           = "personal"
us_region         = "us-east-1"
br_region         = "sa-east-1"
domain            = "otaviomedeiros.com"
sub_domain        = "store.otaviomedeiros.com"
vpc_cidr_block    = "192.168.0.0/16"
